language: perl
perl:
  # - "5.26"
  - "5.24"
  # - "5.22"
  # - "5.20"
  # - "5.18"
env:
  global:
  - LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include -fPIC" LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  matrix:
  - NEO4J_VER=3.5.18
  - NEO4J_VER=3.2.14
matrix:
  allow_failures:
    - env: NEO4J_VER=3.2.14

before_install:
  - curl -O https://dist.neo4j.org/neo4j-community-$NEO4J_VER-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VER-unix.tar.gz
  - neo4j-community-$NEO4J_VER/bin/neo4j start
  - ln -s neo4j-community-$NEO4J_VER/bin/cypher-shell
  # install libneo4j-client
  - cpanm Neo4j::Client
  # perl pkgs
  - cpanm Inline::C Try::Tiny ExtUtils::CChecker Test::Pod Test::CPAN::Changes

install:
  - java -version

  # need to change pass on first access
  - curl -u neo4j:neo4j -d '{"password":"j4oen"}' -X POST -H 'Accept:application/json' -H'Content-Type:application/json' http://localhost:7474/user/neo4j/password
  - cat .sample.cypher | ./cypher-shell -u neo4j -p j4oen 
  
#before_script:
#  - sudo neo4j start

script:
  - echo $'\n'y$'\n'$'\n'neo4j$'\n'j4oen$'\n'y | perl Build.PL
  - cat _build/notes
  - ./Build 
  - ./Build test
