language: perl
perl:
  - "5.30"
  # - "5.28"
  # - "5.26"
  # - "5.24"
services:
  - docker
env:
  matrix:
  - NEO4J_VER=4.2
  - NEO4J_VER=3.5

before_install:
  - docker pull $DOCKERH/testneo/testneo:$NEO4J_VER
  - docker run -P -d -p 127.0.0.1:7474:7474 -p 127.0.0.1:7473:7473 -p 127.0.0.1:7687:7687 --name testneo --env NEO4J_AUTH=none $DOCKERH/testneo/testneo:$NEO4J_VER
  - sleep 20
  # load it with some stuff - note "--network=container:testneo"
  - cat .sample.cypher | docker run -i --network=container:testneo --name cyphershell --entrypoint cypher-shell $DOCKERH/testneo/testneo:$NEO4J_VER
  
install:
  - for dep in JSON::PP URI ExtUtils::MakeMaker Test::Exception Pod::Usage Neo4j::Client Neo4j::Types Mozilla::CA Alien::OpenSSL ; do cpanm $dep ; done ; 
  - echo y$'\n'$'\n'$'\n'$'\n'y | perl Makefile.PL
  - make
  
script:
  - make test
  - docker kill testneo
  - docker rm testneo
  - docker rm cyphershell
  
