language: perl
perl:
  # - "5.26"
  - "5.24"
  # - "5.22"
  # - "5.20"
  # - "5.18"
env:
  - NEO4J_VER=3.0.3 LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include -fPIC" LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  # - NEO4J_VER=2.3.3
  # - NEO4J_VER=2.2.8  
  # - NEO4J_VER=2.1.8
  # - NEO4J_VER=2.0.4
  # - NEO4J_VER=1.9.5

before_install:
  # neo4j pkgs
  - curl https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  # fetch a constant tag
  - git clone https://github.com/cleishm/libneo4j-client.git
  - git fetch --tags --all
  - git checkout tags/v2.2.0 -b v2.2.0
  - pushd libneo4j-client
  - ./autogen.sh
  # --with-pic key for Inline::C compile later
  - ./configure --disable-tools --with-pic --prefix /usr/local
  - sudo make install
  - popd
  # perl pkgs
  - cpanm Inline::C Try::Tiny ExtUtils::CChecker Test::Pod Test::CPAN::Changes

install:
  - java -version
  - echo N | sudo apt-get -y install neo4j=$NEO4J_VER
  - sleep 20

  # need to change pass on first access
  - curl -u neo4j:neo4j -d '{"password":"j4oen"}' -X POST -H 'Accept:application/json' -H'Content-Type:application/json' http://localhost:7474/user/neo4j/password
  - cat .sample.cypher | cypher-shell -u neo4j -p j4oen 
  
#before_script:
#  - sudo neo4j start

script:
  - echo $'\n'y$'\n'$'\n'neo4j$'\n'j4oen | perl Build.PL
  - cat _build/notes
  - ./Build 
  - ./Build test
